"""Export download falls back to S3 when the local file is not on this host.

Reports generated by the scheduled Lambda write their files to the
function's ephemeral ``/tmp``; only the S3 copy outlives the invocation,
so the API must be able to serve from it.
"""

from __future__ import annotations

import io
import os

import pytest
from botocore.exceptions import ClientError

from app.infrastructure.db.models import ReportRun
from app.infrastructure.storage import s3_client

CSV_CONTENT = (
    b"external_id,timestamp,amount,currency,counterparty,raw_category_hint\n"
    b"tx-1,2026-01-05T10:00:00Z,150.00,USD,Acme Corp,\n"
)


@pytest.fixture()
def report_id(client, auth_headers):
    client.post(
        "/api/v1/batches/upload",
        headers=auth_headers,
        files={"file": ("t.csv", CSV_CONTENT, "text/csv")},
    )
    response = client.post(
        "/api/v1/reports",
        headers=auth_headers,
        json={"period_start": "2026-01-01", "period_end": "2026-01-31"},
    )
    assert response.status_code == 201, response.text
    return response.json()["id"]


def _simulate_lambda_report(db_session, report_id: str) -> None:
    """Local files gone (other host), durable copy recorded under S3 keys."""
    run = db_session.get(ReportRun, report_id)
    for path in (run.export_json_path, run.export_csv_path, run.export_pdf_path):
        os.remove(path)
    run.s3_json_key = f"reports/{report_id}/report.json"
    run.s3_csv_key = f"reports/{report_id}/report.csv"
    run.s3_pdf_key = f"reports/{report_id}/report.pdf"
    db_session.commit()


def test_export_is_served_from_s3_when_local_file_is_missing(
    client, auth_headers, db_session, report_id, monkeypatch
):
    _simulate_lambda_report(db_session, report_id)
    requested: list[str] = []

    def fake_download(*, key: str) -> bytes:
        requested.append(key)
        return b"category,currency,metric_name\nfrom-s3\n"

    monkeypatch.setattr(s3_client, "download_object", fake_download)

    response = client.get(f"/api/v1/reports/{report_id}/export?format=csv", headers=auth_headers)

    assert response.status_code == 200
    assert response.text.startswith("category,currency,metric_name")
    assert requested == [f"reports/{report_id}/report.csv"]
    assert response.headers["content-type"].startswith("text/csv")
    assert f'filename="report-{report_id}.csv"' in response.headers["content-disposition"]


def test_local_file_is_preferred_and_s3_is_not_called(client, auth_headers, report_id, monkeypatch):
    def must_not_be_called(*, key: str) -> bytes:
        raise AssertionError("S3 should not be hit when the local file exists")

    monkeypatch.setattr(s3_client, "download_object", must_not_be_called)

    response = client.get(f"/api/v1/reports/{report_id}/export?format=json", headers=auth_headers)
    assert response.status_code == 200


def test_404_when_local_file_missing_and_s3_download_fails(
    client, auth_headers, db_session, report_id, monkeypatch
):
    _simulate_lambda_report(db_session, report_id)
    monkeypatch.setattr(s3_client, "download_object", lambda *, key: None)

    response = client.get(f"/api/v1/reports/{report_id}/export?format=pdf", headers=auth_headers)
    assert response.status_code == 404


def test_404_when_no_local_file_and_no_s3_key(client, auth_headers, db_session, report_id):
    run = db_session.get(ReportRun, report_id)
    os.remove(run.export_json_path)

    response = client.get(f"/api/v1/reports/{report_id}/export?format=json", headers=auth_headers)
    assert response.status_code == 404


class _FakeS3:
    def __init__(self, *, body: bytes | None = None, error: Exception | None = None):
        self._body, self._error = body, error
        self.calls: list[dict] = []

    def get_object(self, **kwargs):
        self.calls.append(kwargs)
        if self._error:
            raise self._error
        return {"Body": io.BytesIO(self._body)}


class TestDownloadObject:
    def test_returns_bytes_for_the_configured_bucket(self, monkeypatch):
        fake = _FakeS3(body=b"payload")
        monkeypatch.setattr(s3_client, "_client", lambda: fake)

        assert s3_client.download_object(key="reports/x/report.json") == b"payload"
        assert fake.calls == [{"Bucket": "compliance-reports", "Key": "reports/x/report.json"}]

    def test_client_error_returns_none_instead_of_raising(self, monkeypatch):
        error = ClientError({"Error": {"Code": "NoSuchKey", "Message": "nope"}}, "GetObject")
        monkeypatch.setattr(s3_client, "_client", lambda: _FakeS3(error=error))

        assert s3_client.download_object(key="missing") is None
