"""initial schema

Revision ID: ddb7318e74f7
Revises: 
Create Date: 2026-09-21 16:19:48.234370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb7318e74f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_row_count', sa.Integer(), nullable=False),
    sa.Column('rejected_row_count', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batches_created_at', 'batches', ['created_at'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rule_set_version', sa.String(length=20), nullable=False),
    sa.Column('rule_set_definition_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='reportrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('input_transaction_count', sa.Integer(), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('export_json_path', sa.String(length=500), nullable=True),
    sa.Column('export_csv_path', sa.String(length=500), nullable=True),
    sa.Column('export_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('s3_json_key', sa.String(length=500), nullable=True),
    sa.Column('s3_csv_key', sa.String(length=500), nullable=True),
    sa.Column('s3_pdf_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_runs_period', 'report_runs', ['period_start', 'period_end'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_run_id'], ['report_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entries_report_run_id', 'audit_log_entries', ['report_run_id'], unique=False)
    op.create_table('report_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_run_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('source_transaction_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_run_id'], ['report_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_line_items_report_run_id', 'report_line_items', ['report_run_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('raw_category_hint', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_batch_id', 'transactions', ['batch_id'], unique=False)
    op.create_index('ix_transactions_timestamp', 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_batch_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_report_line_items_report_run_id', table_name='report_line_items')
    op.drop_table('report_line_items')
    op.drop_index('ix_audit_log_entries_report_run_id', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index('ix_report_runs_period', table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index('ix_batches_created_at', table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
